### ISSUE TITLE
Generator support

### ISSUE THREAD

**Issue by nelix** [ForbesLindesay/halting-problem#6]
haltingProblem.protect is a really cool feature, it would be nice if when a generator is passed in, that halting-problem would turn all functions into generators and yield *haltingProblem.protect.

This would allow for single stepping, or requestIdleCallback loops

**Comment by ForbesLindesay** [comment]
The problem with trying to make something like that is that you have to re-implement all builtin functions that take functions as arguments (e.g. `Array.prototype.map`, `String.prototype.replace`).  It does sound like an interesting project, but it is out of scope for halting-problem.
